<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="7" passed="1" failed="3" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-04T19:34:01 IST" name="Suite" finished-at="2024-07-04T19:34:30 IST" duration-ms="29982">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorsHandingTest.LoginErrorCheck()[pri:0, instance:mypractice.tests.ErrorsHandingTest@2584b82d]" name="LoginErrorCheck" class="mypractice.tests.ErrorsHandingTest"/>
      </group> <!-- ErrorHandling -->
      <group name="purchase">
        <method signature="POMStandaloneTest.submitorder(java.util.HashMap)[pri:0, instance:mypractice.tests.POMStandaloneTest@3f4faf53]" name="submitorder" class="mypractice.tests.POMStandaloneTest"/>
      </group> <!-- purchase -->
    </groups>
    <test started-at="2024-07-04T19:34:01 IST" name="Catch Errors" finished-at="2024-07-04T19:34:21 IST" duration-ms="20878">
      <class name="mypractice.tests.ErrorsHandingTest">
        <test-method is-config="true" signature="navigateApp()[pri:0, instance:mypractice.tests.ErrorsHandingTest@2584b82d]" started-at="2024-07-04T19:34:01 IST" name="navigateApp" finished-at="2024-07-04T19:34:06 IST" duration-ms="5598" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateApp -->
        <test-method retried="true" signature="LoginErrorCheck()[pri:0, instance:mypractice.tests.ErrorsHandingTest@2584b82d]" started-at="2024-07-04T19:34:06 IST" name="LoginErrorCheck" finished-at="2024-07-04T19:34:07 IST" duration-ms="1126" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at mypractice.tests.ErrorsHandingTest.LoginErrorCheck(ErrorsHandingTest.java:26)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorCheck -->
        <test-method is-config="true" signature="closedriver()[pri:0, instance:mypractice.tests.ErrorsHandingTest@2584b82d]" started-at="2024-07-04T19:34:07 IST" name="closedriver" finished-at="2024-07-04T19:34:08 IST" duration-ms="368" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closedriver -->
        <test-method is-config="true" signature="navigateApp()[pri:0, instance:mypractice.tests.ErrorsHandingTest@2584b82d]" started-at="2024-07-04T19:34:08 IST" name="navigateApp" finished-at="2024-07-04T19:34:10 IST" duration-ms="1872" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateApp -->
        <test-method signature="LoginErrorCheck()[pri:0, instance:mypractice.tests.ErrorsHandingTest@2584b82d]" started-at="2024-07-04T19:34:10 IST" name="LoginErrorCheck" finished-at="2024-07-04T19:34:11 IST" duration-ms="1056" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at mypractice.tests.ErrorsHandingTest.LoginErrorCheck(ErrorsHandingTest.java:26)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorCheck -->
        <test-method is-config="true" signature="closedriver()[pri:0, instance:mypractice.tests.ErrorsHandingTest@2584b82d]" started-at="2024-07-04T19:34:11 IST" name="closedriver" finished-at="2024-07-04T19:34:11 IST" duration-ms="351" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closedriver -->
        <test-method is-config="true" signature="navigateApp()[pri:0, instance:mypractice.tests.ErrorsHandingTest@2584b82d]" started-at="2024-07-04T19:34:11 IST" name="navigateApp" finished-at="2024-07-04T19:34:13 IST" duration-ms="1899" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateApp -->
        <test-method signature="ProductErrorCheck()[pri:0, instance:mypractice.tests.ErrorsHandingTest@2584b82d]" started-at="2024-07-04T19:34:13 IST" name="ProductErrorCheck" finished-at="2024-07-04T19:34:21 IST" duration-ms="7795" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorCheck -->
        <test-method is-config="true" signature="closedriver()[pri:0, instance:mypractice.tests.ErrorsHandingTest@2584b82d]" started-at="2024-07-04T19:34:21 IST" name="closedriver" finished-at="2024-07-04T19:34:21 IST" duration-ms="498" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closedriver -->
      </class> <!-- mypractice.tests.ErrorsHandingTest -->
    </test> <!-- Catch Errors -->
    <test started-at="2024-07-04T19:34:01 IST" name="Submit Order" finished-at="2024-07-04T19:34:30 IST" duration-ms="29982">
      <class name="mypractice.tests.POMStandaloneTest">
        <test-method is-config="true" signature="navigateApp()[pri:0, instance:mypractice.tests.POMStandaloneTest@3f4faf53]" started-at="2024-07-04T19:34:01 IST" name="navigateApp" finished-at="2024-07-04T19:34:06 IST" duration-ms="4793" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateApp -->
        <test-method signature="submitorder(java.util.HashMap)[pri:0, instance:mypractice.tests.POMStandaloneTest@3f4faf53]" started-at="2024-07-04T19:34:06 IST" name="submitorder" data-provider="getData" finished-at="2024-07-04T19:34:15 IST" duration-ms="9837" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Kk@123456, email=KKK11@nomail.com, myproductName=ZARA COAT 3}]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.ElementClickInterceptedException">
            <message>
              <![CDATA[element click intercepted: Element is not clickable at point (1049, 580)
  (Session info: chrome=126.0.6478.127)
Build info: version: '4.21.0', revision: '79ed462ef4'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '20.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [a43d1cafe7e5946b75caae58952eb933, clickElement {id=f.53B6C48BE83F97AD27677BC4C25F1B54.d.D95AFCBBE75ED639C3121A8AC57D2B44.e.118}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 126.0.6478.127, chrome: {chromedriverVersion: 126.0.6478.55 (7616ff175414..., userDataDir: C:\Users\GIRISH~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:50283}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:50283/devtoo..., se:cdpVersion: 126.0.6478.127, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on windows (a43d1cafe7e5946b75caae58952eb933)] -> xpath: //a[contains(@class,'action__submit')]]
Session ID: a43d1cafe7e5946b75caae58952eb933]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.ElementClickInterceptedException: element click intercepted: Element is not clickable at point (1049, 580)
  (Session info: chrome=126.0.6478.127)
Build info: version: '4.21.0', revision: '79ed462ef4'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '20.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [a43d1cafe7e5946b75caae58952eb933, clickElement {id=f.53B6C48BE83F97AD27677BC4C25F1B54.d.D95AFCBBE75ED639C3121A8AC57D2B44.e.118}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 126.0.6478.127, chrome: {chromedriverVersion: 126.0.6478.55 (7616ff175414..., userDataDir: C:\Users\GIRISH~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:50283}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:50283/devtoo..., se:cdpVersion: 126.0.6478.127, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on windows (a43d1cafe7e5946b75caae58952eb933)] -> xpath: //a[contains(@class,'action__submit')]]
Session ID: a43d1cafe7e5946b75caae58952eb933
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:223)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:76)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at jdk.proxy2/jdk.proxy2.$Proxy13.click(Unknown Source)
at mypratice.pageobjects.PaymentPage.submit(PaymentPage.java:39)
at mypractice.tests.POMStandaloneTest.submitorder(POMStandaloneTest.java:62)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.ElementClickInterceptedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitorder -->
        <test-method is-config="true" signature="closedriver()[pri:0, instance:mypractice.tests.POMStandaloneTest@3f4faf53]" started-at="2024-07-04T19:34:16 IST" name="closedriver" finished-at="2024-07-04T19:34:16 IST" duration-ms="497" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closedriver -->
        <test-method is-config="true" signature="navigateApp()[pri:0, instance:mypractice.tests.POMStandaloneTest@3f4faf53]" started-at="2024-07-04T19:34:16 IST" name="navigateApp" finished-at="2024-07-04T19:34:18 IST" duration-ms="2365" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateApp -->
        <test-method signature="submitorder(java.util.HashMap)[pri:0, instance:mypractice.tests.POMStandaloneTest@3f4faf53]" started-at="2024-07-04T19:34:18 IST" name="submitorder" data-provider="getData" finished-at="2024-07-04T19:34:28 IST" duration-ms="9922" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Kk@123456, email=KK111@nomail.com, myproductName=ADIDAS ORIGINAL}]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.ElementClickInterceptedException">
            <message>
              <![CDATA[element click intercepted: Element is not clickable at point (1049, 590)
  (Session info: chrome=126.0.6478.127)
Build info: version: '4.21.0', revision: '79ed462ef4'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '20.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [61288ab19199fe0d0b0c3f1c056a9fc9, clickElement {id=f.0E1C34AECF6F6E93A2438E06D8467091.d.A35A1C816FF76CA70D1BBEF0B36DF472.e.122}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 126.0.6478.127, chrome: {chromedriverVersion: 126.0.6478.55 (7616ff175414..., userDataDir: C:\Users\GIRISH~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:50398}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:50398/devtoo..., se:cdpVersion: 126.0.6478.127, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on windows (61288ab19199fe0d0b0c3f1c056a9fc9)] -> xpath: //a[contains(@class,'action__submit')]]
Session ID: 61288ab19199fe0d0b0c3f1c056a9fc9]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.ElementClickInterceptedException: element click intercepted: Element is not clickable at point (1049, 590)
  (Session info: chrome=126.0.6478.127)
Build info: version: '4.21.0', revision: '79ed462ef4'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '20.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [61288ab19199fe0d0b0c3f1c056a9fc9, clickElement {id=f.0E1C34AECF6F6E93A2438E06D8467091.d.A35A1C816FF76CA70D1BBEF0B36DF472.e.122}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 126.0.6478.127, chrome: {chromedriverVersion: 126.0.6478.55 (7616ff175414..., userDataDir: C:\Users\GIRISH~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:50398}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:50398/devtoo..., se:cdpVersion: 126.0.6478.127, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on windows (61288ab19199fe0d0b0c3f1c056a9fc9)] -> xpath: //a[contains(@class,'action__submit')]]
Session ID: 61288ab19199fe0d0b0c3f1c056a9fc9
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:223)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:76)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at jdk.proxy2/jdk.proxy2.$Proxy13.click(Unknown Source)
at mypratice.pageobjects.PaymentPage.submit(PaymentPage.java:39)
at mypractice.tests.POMStandaloneTest.submitorder(POMStandaloneTest.java:62)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.ElementClickInterceptedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitorder -->
        <test-method is-config="true" signature="closedriver()[pri:0, instance:mypractice.tests.POMStandaloneTest@3f4faf53]" started-at="2024-07-04T19:34:28 IST" name="closedriver" finished-at="2024-07-04T19:34:30 IST" duration-ms="1981" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closedriver -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:mypractice.tests.POMStandaloneTest@3f4faf53]" started-at="2024-07-04T19:34:30 IST" name="OrderHistoryTest" finished-at="2024-07-04T19:34:30 IST" depends-on-methods="mypractice.tests.POMStandaloneTest.submitorder" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method mypractice.tests.POMStandaloneTest.OrderHistoryTest() on instance mypractice.tests.POMStandaloneTest@3f4faf53 depends on not successfully finished methods 
[mypractice.tests.POMStandaloneTest.submitorder() on instance mypractice.tests.POMStandaloneTest@3f4faf53]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method mypractice.tests.POMStandaloneTest.OrderHistoryTest() on instance mypractice.tests.POMStandaloneTest@3f4faf53 depends on not successfully finished methods 
[mypractice.tests.POMStandaloneTest.submitorder() on instance mypractice.tests.POMStandaloneTest@3f4faf53]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
      </class> <!-- mypractice.tests.POMStandaloneTest -->
    </test> <!-- Submit Order -->
  </suite> <!-- Suite -->
</testng-results>
